[package]
name = "nsv-ffi"
version = "0.1.0"
edition = "2021"

[dependencies]
nsv = { git = "https://github.com/nsv-format/nsv-rust.git", branch = "claude/update-nsv-duckdb-eNCLr" }

[lib]
crate-type = ["staticlib"]
